### ISSUE TITLE
Latest docker image, not working?

### ISSUE THREAD

**Issue by michelbetancourt** [kennedyoliveira/standalone-hystrix-dashboard#3] opened 2016-09-19 18:35 UTC
I've tried your latest docker image and it does not appear to work.  Any thoughts?

``` bash
docker run --rm -ti -p 7979:7979 kennedyoliveira/hystrix-dashboard

18:33:01.181 [vert.x-eventloop-thread-1] INFO  c.g.k.h.c.s.d.HystrixDashboardVerticle - Initializing the HystrixDashboardVerticle instance 1
18:33:01.210 [vert.x-eventloop-thread-1] INFO  c.g.k.h.c.s.d.HystrixDashboardVerticle - Compression support enabled: true
18:33:01.344 [vert.x-eventloop-thread-1] INFO  c.g.k.h.c.s.d.HystrixDashboardVerticle - Listening on port: 7979
18:33:01.344 [vert.x-eventloop-thread-1] INFO  c.g.k.h.c.s.d.HystrixDashboardVerticle - Access the dashboard in your browser: http://localhost:7979/hystrix-dashboard/
18:33:01.346 [vert.x-eventloop-thread-0] INFO  i.v.c.i.l.c.VertxIsolatedDeployer - Succeeded in deploying verticle
```

Via browser or Curl: 

``` bash
curl -v "http://localhost:7979/hystrix-dashboard/"
*   Trying ::1...
* Connected to localhost (::1) port 7979 (#0)
> GET /hystrix-dashboard/ HTTP/1.1
> Host: localhost:7979
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Length: 9
<
* Connection #0 to host localhost left intact
Not Found%
```

**Comment by kennedyoliveira** [comment] 2016-09-20 03:37
Hey @michelbetancourt!

Thanks for your feedback, it was working, i just tried it now and looks like not working, really don't understand, tomorrow i'll take a closer look, as a workaround, you can use the version 1.5.2, with the command `docker run --rm -ti -p 7979:7979 kennedyoliveira/hystrix-dashboard:1.5.2` or if you can download the fatjar direct from bintray (clicking in the download badge on readme), you can get a dashboard up and running pretty easily too.

I'm waiting on a new hystrix release to release a new version and improve some code too, because i improved the dashboard in this PR https://github.com/Netflix/Hystrix/pull/1336, but i didn't expect the current version not working, since it was working, anyway, i'm gonna check it and fix whatever needs to be fixed and report back to you.

Sorry for the inconvenience.

**Comment by grissomsh** [comment] 2016-09-21 06:59
I also tried, 1.5.2 works, 1.5.3 doesn't work.

No log info is useful to locate the root cause.

**Comment by kennedyoliveira** [comment] 2016-09-21 07:49
Hey @grissomsh, I found the problem, more or less, bintray changed the URL I used to make the image, and then it failed the last update I did to image, I don't know what version is in this 1
5.3, but there are almost no difference between 1.5.3 and 1.5.2, I'm going to do a surgery in a couple of hours, and will be unable to use the computer maybe for just 2 days, after I came back to home i'll generate a new image, sorry for the inconvenience.

**Comment by michelbetancourt** [comment] 2016-09-21 14:30
look forward to the update, thanks.

**Comment by unindented** [comment] 2016-10-03 15:48
@kennedyoliveira Hope the surgery went ok... Less importantly, did you get the chance to push the new image?

**Comment by kennedyoliveira** [comment] 2016-10-03 17:40
Hey everyone, my surgery went ok, i'll try to push the new version with a new docker image today! Sorry for the delay.

**Comment by kennedyoliveira** [comment] 2016-10-04 00:11
hey everyone, i just released a new version, but the docker hub is taking a while to build the image, but there's a 1.5.6 version, if you guys could try and give a feedback, the latest will be the same as this 1.5.6.

**Comment by kennedyoliveira** [comment] 2016-10-04 02:59
The latest docker image is available now, i tested here and is working, waiting on your feedbacks.

**Comment by unindented** [comment] 2016-10-04 07:58
Working perfectly for me too. Thank you @kennedyoliveira!

**Comment by kennedyoliveira** [comment] 2016-10-05 01:54
@unindented thanks for the feedback, i'm glad it's working!
@michelbetancourt, @grissomsh did you guys tried the new image?

**Comment by grissomsh** [comment] 2016-10-05 13:28
@kennedyoliveira I have forked your Dockfile and changed the version a little bit:

RUN curl https://repo1.maven.org/maven2/com/netflix/hystrix/hystrix-dashboard/1.5.6/hystrix-dashboard-1.5.6.war -o hystrix-dashboard.war

RUN curl https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-runner/9.3.9.v20160517/jetty-runner-9.3.9.v20160517.jar -o jetty-runner.jar

It works now (But I haven't try your image yet)

**Comment by kennedyoliveira** [comment] 2016-10-05 18:06
@grissomsh i see, well, if you want to give a try again, it's working fine.

**Comment by kennedyoliveira** [comment] 2016-10-14 15:32
closing the issue since it's working, if need any more discussion, please reopen.

**Closed as completed by kennedyoliveira** 2016-10-14 15:32 UTC
